### ISSUE TITLE
spell-check throws an error at atom launch

### ISSUE THREAD

**Issue by karthanistyr** [atom/spell-check#253]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
  * [x] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
  * [x] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
  * [x]  Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
  * [x]  Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
  * [x] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
A default installation of Atom on a fresh non-US system (arch linux) throws an error through the spell-check module.

*Note that this is about broken default settings, and is different from #11 which is related to supporting multiple dictionaries at once.*

Upon launch of `atom`, a red popup error message appears with the message:
```
Cannot load the system dictionary for `fr_FR`. Checked the following paths for dictionary files:
* /usr/share/hunspell
* /usr/share/myspell
* /usr/share/myspell/dicts
* /usr/lib/atom/node_modules/spellchecker/vendor/hunspell_dictionaries
```
![spellchk](https://user-images.githubusercontent.com/7722196/39394798-680aaf26-4b00-11e8-98a3-e6ea0b6cb930.png)

### Steps to Reproduce

1. Ensure the system default locale is **not** en_US
2. Ensure none of the system dictionary folders exist (respective packages not installed), or at least do not provide a dictionary file for the system default locale
3. Ensure Atom's spell-check settings are setup to load the system default locale dictionary
![spellchk-locales](https://user-images.githubusercontent.com/7722196/39394850-13438034-4b01-11e8-9528-9f5435333438.png) 
4. Launch `atom`

**Expected behavior:** 

There should be no error message on systems using a non-US locale as a default. Instead, spell-check should either work on a non-US locale, or be disabled in a graceful way.

**Actual behavior:**

An error is thrown and spell-check does not work.

**Reproduces how often:** 

Always reproduces.

### Versions
Arch Linux x64 (patched to latest as of writing)

```
% atom --version
Atom    : 1.26.1
Electron: 1.8.4
Chrome  : 59.0.3071.115
Node    : 8.2.1
% apm --version
apm  1.19.0
npm  5.8.0
node 9.11.1 x64
atom 1.26.1
python 2.7.14
git 2.17.0
```

### Additional Information

Atom only seems to provide an en_US dictionary as a fallback mechanism. This is unsuitable for systems that set a default local other than en_US.

Note that this is regarding a system that hasn't got its own spellcheck (hunspell or otherwise) dictionaries installed.

I'm unsure if it is reasonable to expect a fallback for all locales, but if it is not, then I wonder how justified it is to be shipping a en_US fallback dictionary alone. If spell-check is to be a default module, and hunspell is not a dependency of Atom, then I think spell-check should work in all locales, and that may mean shipping a fallback dictionary for each.

**Comment by pabloab** [comment]
Same here with spell-check@0.73.4 starting some days ago, probably due to an update.

Console log:

    spell-check:en-en Cannot load the system dictionary for `en-EN`. Checked the following paths for dictionary files:
    * /usr/share/aspell/
    * /usr/share/hunspell
    * /usr/share/myspell
    * /usr/share/myspell/dicts
    * /usr/share/atom/resources/app.asar.unpacked/node_modules/spellchecker/vendor/hunspell_dictionaries
    <embedded>:119660 spell-check:es-es Cannot load the system dictionary for `es-ES`. Checked the following paths for dictionary files:
    * /usr/share/aspell/
    * /usr/share/hunspell
    * /usr/share/myspell
    * /usr/share/myspell/dicts
    * /usr/share/atom/resources/app.asar.unpacked/node_modules/spellchecker/vendor/hunspell_dictionaries
    <embedded>:119660 spell-check:es-ar Cannot load the system dictionary for `es-AR`. Checked the following paths for dictionary files:
    * /usr/share/aspell/
    * /usr/share/hunspell
    * /usr/share/myspell
    * /usr/share/myspell/dicts
    * /usr/share/atom/resources/app.asar.unpacked/node_modules/spellchecker/vendor/hunspell_dictionaries

Setup:
* Locales: en-EN, es-ES, es-AR
* Locale path: /usr/share/aspell/

System packages and versions:
* **aspell** 0.60.7~20110707-3build1, **aspell-en** 7.1-0-1.1, **aspell-es** 1.11-14
* `atom --version` Atom    : 1.26.1 Electron: 1.7.11 Chrome  : 58.0.3029.110 Node    : 7.9.0
* `apm --version` apm  1.19.0 npm  3.10.10 node 6.9.5 x64 atom 1.26.1 python 3.6.4 git 2.7.4

**Comment by WBGSReject** [comment]
Same here with en-GB. Seems to have happened recently - a few days ago. Sorry I cannot be more specific. I had run Atom with no errors for a few months before this.
Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
Platform - Xubuntu 16.04.4 LTS

**Comment by MonkeyInWind** [comment]
![image](https://user-images.githubusercontent.com/34543887/39608833-e1f8f8ae-4f76-11e8-81ad-e17f6f9e6583.png)

**Comment by Awebb** [comment]
This is an error message in red, that is brought to the user's attention every time we start Atom. The error message talks about missing files, but I do not see a hint on which plugin I'm supposed to check. The error message should at least contain the name of the plugin and maybe a hint, that this can be solved by simply setting the right locale.

**Comment by ChawkiS** [comment]
Hi All;
Same here ! 
win 10 pro x64 fr (high sierra bootcamp partition)
<img width="360" alt="image sans titre" src="https://user-images.githubusercontent.com/38982398/39637273-c06fe296-4fc2-11e8-86ef-78cf475ad05b.png">

**Comment by magicBeast** [comment]
I just installed atom to a recent install of the new Ubuntu 18.04 LTS release and had this message. My region was set to English (United Kingdom) and Input sources to English (UK). However, after some investigation, the system dictionary files are NOT installed by default for the set region and language (which seems silly - I should have been cursing Ubuntu and not atom :-) ). If you click on Manage Installed Languages it tells you that the installation is not complete and installs the missing files. Atom is then able to find them in the default locations that it searches within (the directories mentioned in the red warning message).
    So what appears to be happening is that atom is picking up the set region, in my case en-GB, then looking where it should correctly expect to find the relevant dictionary files, and upon not finding them, throws a warning. So it is actually good, useful behaviour (at least in the case of my Ubuntu install, not sure if this is the case with 16.04, but I suspect it will be the same issue) - it's letting you know you don't have the necessary dictionary files installed.

**Comment by ylansegal** [comment]
@magicBeast Do you know where the locale comes from? I am on a mac and I see this:

```
$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

When I start-up Atom, I see a warning about `sp-MX`.
![screen shot 2018-05-04 at 9 48 11 am](https://user-images.githubusercontent.com/561180/39640628-7336eaf2-4f80-11e8-8b2c-8eb9461683da.png)

Where is that coming from?

**Comment by ChawkiS** [comment]
Thank u magicBeast 👍 
I just installed the missed language pack (in my case en_US) and it solved the issue
no more error popup at Atom launch
<img width="354" alt="image sans titre" src="https://user-images.githubusercontent.com/38982398/39640713-25b55a4c-4fcc-11e8-8cfb-d0e981ec6738.png">

**Comment by dmoonfire** [comment]
How about:

1. Make it a warning instead of an error.
2. Change the first sentence to start with "The package `spell-check` cannot load a system dictionary...`
3. Put a little more advice before the search path:
    * For Windows 10, "You may need to install the missing language from your Region & Language settings."
    * For Mac OS, "You may need to install the missing language from your system settings."
    * For Linux: "You may need to install the missing language package (such as `apt install hunspell-REGION`) from your package manager."
4. Add "To change which languages are used by `spell-check`, change the 'Locales' settings in the plugin's configuration or uncheck 'Use Locales' to disable spell-checking".

Would that help? Would it still be acceptable to show on every startup?

**Comment by Awebb** [comment]
It's enough if the user sets the spell check locale to an installed locale (de-DE in my case). It might be a good idea to auto detect the locale during the installation. IMO it would be enough to add a line to the error message, that tells the user to install the language files and/or set the locale in the plugin. I'd also appreciate the error message stating the name of the plugin.

Does the error massage allow to have a button, that directly calls the plugin settings? I have no idea yet how Atom works internally.

**Comment by dmoonfire** [comment]
![image](https://user-images.githubusercontent.com/206815/39657153-e929519c-4fca-11e8-8178-2b5448e617ab.png)

I've pushed up a PR for this, see the link above.

**Comment by Awebb** [comment]
I like it. The package name is in the message, so we know what to do without diving in to deep.

As a side note, I think people are having different errors. Some of us get a message about their actual locale not being there, but I'm on Windows with an intact de-DE and it complains about a missing en-US.

**Comment by Awebb** [comment]
I tested it again, this might be a different bug. It says "if this is blank, then the default language for the user will be used", but it assumes en-US on my de-DE system. If I manually set de-DE in spell-check or install atom-i18n and set it to DE, then the message does not appear. Separate bug report?

**Comment by dmoonfire** [comment]
@Awebb: Separate item, please. The code that assumes the locale if one isn't set is in a different point of code. Right now, on Linux, it uses the `LANG` environment variable to figure out default language code. If that is wrong, it probably has an entirely different fix. :)

**Comment by karthanistyr** [comment]
@dmoonfire thank you for spending time on this issue. I am not convinced that replacing a cryptic error with a slightly less, but still cryptic (i.e. what « language package »?) warning at startup is much better.

I believe the spirit of the original issue is that the default installation of atom (and hence, spell-check) makes assumptions about the system, and by getting them wrong throws up an error (now a warning). I’d like to see atom behave gracefully out of the box, and not making the user do more work to accomodate for its default configuration.

Here are some undiscussed  concerns (raised in the original post):

* why is spell-check enabled by default when atom doesn’t guarantee that it will be able to load and function?

* how do you stand on fallback dictionaries? there was once a decision to ship hunspell bundled in node-spellchecker (backend to spell-check) (see https://github.com/atom/node-spellchecker/commit/f4d7973598477c147af47a574db3e91f6185ab64) along with a singular en_US fallback dictionary, *which is still used as fallback as of writing*. This solves the error for en_US, albeit probably will then eventually have the text be checked against a non-optimal, outdated dictionary without the user’s knowledge with no prompt to install a better one (and be another issue in itself).

* is there really no alternative than a big, in-your-face message at every startup until the user takes action? (again it’s a bit of a bother given it’s in a default configuration, it gives the wrong impression)

* if the message has to stay... please make it better, especially for Linux. Can you not provide a URL to a wiki page where you have all liberty to explain in detail the remediation steps? Note the error tooltip is already too small to dislay the entire message so it’s not great to be too verbose in it.

**Comment by dmoonfire** [comment]
I suspect many of the decisions came from a primary English-based developers who never needed more than the fallback. In my case, I needed multiple locales and project level dictionaries which is why I rewrote the plugin infrastructure for spell checking. Along the way, I figured I'd solve the "doesn't work at all outside of US English".

The problem I was solving with the original PR was that Atom didn't tell anyone when it wasn't working, nor was their any way of figuring out why it wasn't working. So, using your environment as an example, spell check would quietly refuse the work and not give any feedback unless the user happened to open up the console for the cryptic "Couldn't load de-DE."

Effectively, spell-check was disabling itself if there was no dictionary. It was just not telling anyone when it happened. If you look at the other issues, there were a number of "it doesn't work, why!?"

An alternative would be to have something in the status bar that says spell-checking isn't working, but that was more than I had the bandwidth for in this iteration; I also didn't realize there were situations when the OS didn't have the default language for hunspell installed.

Fallback dictionaries? I dislike them because they are opaque. I'd rather have it as an Atom-installable `spell-check-en-us` package. The new plugin infrastructure will allow it now, no one has written it yet. (This is also why I made "Use Locales" a checkbox in the settings, to allow for the system one to be disabled in favor of something the user can see.) Also packages would allow it to be upgraded properly. :) I'm also not fond of the fallback to the OS dictionaries for Windows and Mac, I'd rather see those as plugins also. However, I still feel this is above my pay grade.

Please give me a link to use? I'll be glad to use it, I just haven't found a good, generic page to handle dictionary installation that handled different flavors of Linux.

As for the in-your-face, I don't know any method at this point for subtle error indicators. Eventually, I'd like to see something in the status bar or tied into the linter (my preference) but that is a different issue/PR to do it properly. If there is one, I'll be glad to use it. I'm just not aware of one.

**Comment by dmoonfire** [comment]
There is an option to write to console, popup, or both. I could make it console only by default but it would require someone to switch an option.

**Comment by karthanistyr** [comment]
@dmoonfire I understand your reasons for introducing this message in the first place was to make the user aware that the plugin wasn't working when it could have been assumed that it was -- and caused the "why doesn't it work?" issues you are referring to. I also understand your need to not pour an infinite amount of time and effort into this one issue.

Can another alternative be an error, or warning, message inside the settings page of the plugin itself?

I believe it would strike in the middle ground (although I am not aware if this is possible to implement). When the plugin can't load the desired dictionary (whatever the configuration, be it "Use system locale" or "specific dictionary"...):

* No error at startup
* Spell-checking doesn't work
* When the user goes into the settings to see why, an explicative message points to the problem and solution (guarding against users opening issues here to enquire why)

Additional issues can be opened to track:

* Installing dictionaries as atom plugins instead of system packages
* make spell-check rely on those for spellchecking
* notifying the user via status bar if that's still required

**Comment by s-xync** [comment]
I solved this problem by going into manage packages and navigating to spell-check package. Then go into it's settings and then you will find a text box that asks for list of locales. Just add en-US there if and make sure that language is installed on your system. It's done.

**Comment by liuliangsir** [comment]
@s-xync I run into another problem that how to install language on system after I follow some steps you provided

**Comment by vsag** [comment]
@magicBeast  For me it says en_IN dictionary files are missing, in the language support I don't have English india, do you have an idea what I can do? Like you've said it showed a prompt while clicking install/remove languages about not being installed , so can you tell me anything more I can try. On a side note what features would I miss out on because of this error? I use atom only for programming purposes and does this affect the features for programming side of things?

Thanks

**Comment by dmoonfire** [comment]
If you don't want spell-checking, go into the settings for `spell-check` and uncheck "Use Locales". If you want a different language, put the language code (such as `en-US`) in the "Locales". I have a PR (https://github.com/atom/spell-check/pull/255) submitted to reduce the severity of the error (making it default to console instead of popup, differently worded).

**Comment by vsag** [comment]
@dmoonfire  thanks, but for some reason I've just did a reboot and the error no longer shows. Thanks anyways. I think the solution is given by @magicBeast.

**Comment by mitchell486** [comment]
> If you don't want spell-checking, go into the settings for spell-check and uncheck "Use Locales". If you want a different language, put the language code (such as en-US) in the "Locales". I have a PR (#255) submitted to reduce the severity of the error (making it default to console instead of popup, differently worded).

To expand on this... The error states it was looking in `/` and `/System/Library/Spelling` and then another location that appears to be specific for atom on Mac OS. This was cumbersome for me because I wanted to have spell check, but could not find the folders it was referring to. However, I did find out that my _User_ spelling dictionary and default language are stored in my _User_ library. Therefore, I put `~/Library/Spelling` in the Locale Paths for MAC and it seems to have allowed me to have spell check enabled, but removes this error. If you take @dmoonfire's suggestion from above, it simply disables spell check for me. I hope this helps someone in the future! Thank you all for the guidance and help to this point. I appreciate it!

**Comment by virus-warnning** [comment]
![cannot-load-dict-zhtw](https://user-images.githubusercontent.com/5044734/40154262-15f517a2-59c0-11e8-8414-320ec46ddb4f.png)

```!sh
$ atom --version
Atom    : 1.27.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

**Comment by generic-user** [comment]
I have all same issues as already reported above. I can't get any other language working besides the default one.

My dictionary files are located in the specified folder. It just seems the plug-in is not able to find them.
So even with all recommendations given in this thread, I can't seem to get spellchecking working with a **custom defined dictionary**.

I'm using windows 7. The language dictionary is **not** installed as language pack, as I am not able to install those on this machine. **So if you want to reproduce the error make sure u try with a language that is not installed** system wide.

Thanks in advance, ...

**Comment by b52** [comment]
I cannot even get the default system language to work...

**Error message and settings:**
![error-atom](https://user-images.githubusercontent.com/23704/40410544-6226741a-5e6e-11e8-830c-ed3dc07759d2.jpg)

**Region settings:**
![region](https://user-images.githubusercontent.com/23704/40410663-ab9dd3ae-5e6e-11e8-8073-411054236a8e.jpg)

**Local dictionaries shipped with Atom:**
![files](https://user-images.githubusercontent.com/23704/40410693-b83a4ae8-5e6e-11e8-9d55-e39302afc555.jpg)

So if I'm not mistaken, everything should work, shouldn't it? Has anyone a few pointers for me?

**Comment by dmoonfire** [comment]
@b52: node-spellchecker does things differently on Windows 10 (it doesn't bother with en_US.dic). But it should work. What you showed was what I used when I was testing it, so I'm not sure what is going wrong.

**Comment by Fazali-Illahi** [comment]
On Ubuntu 18.04 LTS, I got the same error (en_IN Locale) 
I managed to resolve the issue by installing the  Language Packs from Language Support Settings.

**Comment by monolux** [comment]
Windows 10 

> Cannot load the system dictionary for en_US. Checked the following paths for dictionary files:
> 
> C:\Users\...\AppData\Local\atom\app-1.27.1\resources\app.asar.unpacked\node_modules\spellchecker\vendor\hunspell_dictionaries

I do have en_US.aff, en_us.dic and README.txt in above folder.
This started happening yesterday.
What can be done about it please?
Default OS system language is a different one.
Thank you for any help or pointers.

**Comment by ccoenen** [comment]
after installing english from region settings in Win 10, the message is gone. I'm glad this error message exists - even if it is not perfect (yet). Before, I wouldn't have known that the spellchecker was silently disabled and my system was not configured correctly.

![grafik](https://user-images.githubusercontent.com/124909/40610443-ad99e212-6272-11e8-96d5-9ab0618f3610.png)

**Comment by BrianSidebotham** [comment]
I had this on linux mint 18 - simple fix was to `sudo apt-get install myspell-en-gb`. Was handy to know there was a problem with the new pop-up as I didn't know there was any problem!

**Comment by 0x92** [comment]
@ylansegal Thats the way to fix it.

Had the same error needed to add in the locales "de-DE" and vôila

thank you

**Comment by criskubiaki** [comment]
I was having same issue with W10:

"atom Cannot load the system dictionary for en-US. Checked the following paths for dictionary files:"

I am from Brazil and I had only Portuguese dictionary at that time, to fix my issue I just installed the en-US dictionary:

![image](https://user-images.githubusercontent.com/9754807/41479621-2bc50c7e-70a2-11e8-8b79-32b5f4f4a666.png)

**Comment by prahladyeri** [comment]
If you are on Linux/Ubuntu, then you can do following things:

1. Ensure that `Language Support` is fully installed. Just open that applet from your Ubuntu Dash or XFCE Whisker menu and it will prompt you if its not installed.
2. If that still doesn't solve the problem, then it means Atom isn't using one of your installed locales. Run `ls /usr/share/hunspell` to see which locales you have installed on your system (such as `en_US, en_GB, etc.`). Then go to Atom=>Edit=>Preferences=>Packages, search for "spell check" and then click on its "Settings" button. Then scroll over to locales text-box below and just enter one of those locales there:

![spellcheck_package_setting](https://user-images.githubusercontent.com/5732256/41501219-db932a7a-71bd-11e8-8288-a0f3c5a652c8.png)

**Comment by jackstrain** [comment]
I fixed this on Arch Linux by running `pacman -S hunspell-en_GB` then `cd /usr/share/hunspell` to go to the directory where the dictionary has been installed, then duplicate the two files with a slightly different name so Atom recognises it: `cp en_GB-large.dic en_GB.dic` `cp en_GB-large.aff en_GB.aff`

**Comment by smiffy6969** [comment]
Thanks jackstrain.... worked a charm on manjaro ;)

**Comment by dmoonfire** [comment]
@jackstrain: Could you please add that as a separate issue? I think `spell-check` should just work, but search paths and figuring out files would be out of scope for this specific issue.

@prahladyeri, @criskubiaki, @BrianSidebotham, @ccoenen: Thank you for details. I've pushed up https://github.com/atom/spell-check/pull/255 to be reviewed that includes that information in the read me in a section on how to resolve spelling issues.

@monolux: On Windows 10, we don't actually search that folder unless a specific environment variable is included. I'll add a clarification in the message for that. Thank you.

**Comment by juliaanvaneijndt** [comment]
@dmoonfire 
on macOS High Sierra 10.13.5, atom --version 1.28.0
<img width="465" alt="2018-06-27 a 12 01 56" src="https://user-images.githubusercontent.com/22910267/41964309-4fd04ebc-7a02-11e8-846a-d374251d88e9.png">

grc_GR is a custom dictionary;  it is in ~/Library/Spelling, as well as fr_FR and en_GB 
locale and locale path are set accordingly in atom spell-check preferences

<img width="734" alt="2018-06-27 a 12 01 33" src="https://user-images.githubusercontent.com/22910267/41964288-42949244-7a02-11e8-98ef-4c4f45e88aaa.png">

 fr_FR and en_GB do work

The problem is not with the PATH, probably rather with macOS system spelling (automatic by language): fr_FR, en_GB work / grc_GR not working (see also [this](https://github.com/atom/spell-check/issues/204#issuecomment-329958531))

**Comment by dmoonfire** [comment]
@juliaanvaneijndt: I tried to qualify it in the PR above, but Windows 10 and macOS both use the system dictionaries, not any path. However, I can't hide a configuration setting based on setting so it isn't exactly obvious that we're ignoring the paths in those two situations.

**Comment by MAK947** [comment]
I use Ubuntu 16.04 and I am getting same error msg. How to fix this?

**Comment by wawhal** [comment]
Just install `hunspell` in your system and this error will not show up. It is mainly because the dictionary associated with your region is not present in your system. 

@MAK947 for ubuntu, just run `sudo apt install hunspell` and restart atom. That should fix it. :-)

**Comment by MAK947** [comment]
@wawhal  didnt work:(

**Comment by dmoonfire** [comment]
@MAK947: Try installing Language Services for that language. Also, `sudo apt-get install hunspell-en-gb` might work (replace en-gb with the language you are trying to use).

**Comment by russaa** [comment]
an additional note for Windows 10 users:

when installing additional language packs Windows automatically enables the short-cut CTRL-SHIFT for switching keyboard layouts -- which I accidentally entered often enough to annoy me to the point that I uninstalled all language packs except the default one.

However, this issue somewhat forced me to look at that problem again:

there is actually a solution to disable/change the short-cut for switching the keyboard layout when multiple language packs are installed -- see topic [Keyboard language keeps changing in Windows 10](https://superuser.com/a/991729/627849) on superuser.com:

> In Windows 10, by default, pressing <kbd>CTRL</kbd>+<kbd>SHIFT</kbd> (or for some <kbd>ALT</kbd>+<kbd>SHIFT</kbd> - thanks madmenyo ) will cycle through any keyboard layouts that you might have mapped and it's surprisingly easy to do this by mistake.
>
> If you keep pressing <kbd>CTRL</kbd>+<kbd>SHIFT</kbd> (or whatever you might have changed it to) then soon you should get back to the correct setting. (alternatively reboot which is what I did first time ;-) ) 
>
> You can disable this default keyboard action as follows:
> 
> `Control Panel` > `Clock, Language, and Region` > `Language` > `Advanced settings` > `Switching input methods` > `Change language bar hotkeys` > `Change key sequence...` > `Switch keyboard layout` > `Not Assigned`
>
> from 2016 onwards location has changed. (from comments)
>
> `Control panel` > `Language` > `Advanced settings` > `Switching input methods` > `Change language bar hot keys` 
>
> Be warned, the above doesn't always work - Restarts and Sleep mode can both change keyboard default (usually to US) - I've found no cast-iron solution though creating a new profile can help, though not a particularly satisfactory answer IMHO.
>
> In an emergency
>
>    WIN+R  
>    osk
>
> to bring up the On Screen Keyboard might help temporarily.
>
> Also note that it's possible to disable this so that no key combination will change the language - change the keys to "Not Assigned" - see answer below from Mort for more info

**Comment by ChemBioScripting** [comment]
Same here, for Italian language on Linux Fedora 26 XFCE. Solved in this way:

$ dnf provides hunspell
hunspell-1.5.4-2.fc26.i686
$ sudo dnf install hunspell
$ sudo dnf install hunspell-it

Then, in Atom Settings -> Packages -> spell-check -> Settings -> Check "Use Locales" and, in "Locales" textarea add it-IT (in my case, for Italian language: see attached screenshots).

![istantanea_2018-07-11_15-55-52](https://user-images.githubusercontent.com/3897212/42577371-7347f138-8524-11e8-8ba7-16919dcec94d.png)

![istantanea_2018-07-11_15-56-46](https://user-images.githubusercontent.com/3897212/42577435-9df9bc86-8524-11e8-8494-69c119aee91c.png)

**Comment by dmoonfire** [comment]
We just merged in the changes into the main code. It should show up for the v1.30. This will include more detail on the read me for the plugin to give suggestions on how to fix it, a simplified warning (not error) popup, and more details in the console.

**Comment by blueclaws** [comment]
On arch linux you have hunspell-en package. 
Installing this package fixed the issue for me.

**Comment by gut5** [comment]
`The package spell-check cannot load the system dictionary for en_GB. See the settings for ways of changing the languages used, resolving missing dictionaries, or hiding this warning.
Settings` 

still happening on 1.30-beta-1

**Comment by PogHallam** [comment]
Had the same problem (Ubuntu 18.04): "Cannot load the system dictionary for en_GB"
Solution for me:
> sudo apt-get install hunspell
> sudo apt-get install hunspell-en-gb

**Comment by devtrickhub** [comment]
I just disabled it to fix the problem hahaha you dont need a spellchet at all

**Comment by ccoenen** [comment]
Hi @devtrickhub, this is not a good place to ask this. This is a question more suited for [atom's forum](https://discuss.atom.io/) or a Q&A thing like [Stackoverflow](https://stackoverflow.com/).

These issue trackers are usually for bugreports or feature requests.

Another hint: these issues are usually just meant for one thing. So taking an issue to one topic (in this case: spell check throws an error ...) and going in a different direction is not a good idea. You'll usually not get any answers in such cases.

**Comment by navjotjsingh** [comment]
@Fazali-Illahi Thanks for that. It worked on Ubuntu 18.04.

**Comment by 88Anja88** [comment]
Hi I had the bug in yellow with Fedora 28 and the original rmp file from the Atom site. In the manual of spell-check https://atom.io/packages/spell-check it was stated that you can install the required language with hunspell. Said done and the warning was gone. 
`sudo dnf install hunspell-de`

**Comment by MichaelHabib** [comment]
**On Xubuntu18 using latest Atom ** , i got the error "The package spell-check cannot load the system dictionary for en-AU." due to a missing language package. Solved it by running 
```
sudo apt-get -y install `check-language-support -l ???`
```
Where ??? is your local language code, for me it's `en_AU` .Keep in mind the check-language is quoted with the back-tick and not single quotes.

**Comment by Holyprogrammer** [comment]
> Same here with en-GB. Seems to have happened recently - a few days ago. Sorry I cannot be more specific. I had run Atom with no errors for a few months before this.
> Atom : 1.26.1
> Electron: 1.7.11
> Chrome : 58.0.3029.110
> Node : 7.9.0
> Platform - Xubuntu 16.04.4 LTS
> 
> Some more detail:
> 
> I opened Xubuntu Langauge Support which reported there was a problem:
> 
> ![image](https://user-images.githubusercontent.com/4706996/39641503-5128c9ee-4fc6-11e8-8316-22e07919005f.png)
> 
> ...this is the full list from the dialog box:
> 
> libreoffice-l10n-en-za
> thunderbird-locale-en-gb
> hunspell-en-au
> hyphen-en-gb
> hunspell-en-gb
> libreoffice-help-en-gb
> gimp-help-en
> hunspell-en-ca
> mythes-en-au
> hunspell-en-za
> libreoffice-l10n-en-gb
> 
> I clicked on "install" and after some files were installed I launched Atom and there was no red error message this time.

This Absolutely Works on all ubuntu distros, not only Xubuntu

**Comment by joshcangit** [comment]
Atom on Linux will by default use your system's default locale and throw this error on every launch.
You need to make sure **spell-check** in the **config.cson** file is set as this.
```
  "spell-check":
    locales: [
      "en-US"
    ]
```
If you want to use Atom in a locale other than US English then you better hope the developers eventually solve this bug before it closes and is left hanging forever.

**Comment by PogHallam** [comment]
> Atom on Linux will by default use your system's default locale and throw this error on every launch.
> You need to make sure **spell-check** in the **config.cson** file is set as this.
> 
> ```
>   "spell-check":
>     locales: [
>       "en-US"
>     ]
> ```
> If you want to use Atom in a locale other than US English then you better hope the developers eventually solve this bug before it closes and is left hanging forever.

Or try some of the solutions posted further up on this thread, of which at least one worked on Linux for me.

**Comment by virtualmix** [comment]
I resolved this issue on my machine.
By default the "Locales" value was "**en-us**". I replaced it with "**en-US**" and now spellcheck works.
_Atom 1.34.0 x64 on Debian using the deb package from atom.io._

**Comment by smac89** [comment]
On Arch linux, I did:

`pacman -S hunspell-en_US`

**Comment by herpus-derpus** [comment]
> Same here with en-GB. Seems to have happened recently - a few days ago. Sorry I cannot be more specific. I had run Atom with no errors for a few months before this.
> Atom : 1.26.1
> Electron: 1.7.11
> Chrome : 58.0.3029.110
> Node : 7.9.0
> Platform - Xubuntu 16.04.4 LTS
> 
> Some more detail:
> 
> I opened Xubuntu Langauge Support which reported there was a problem:
> 
> ![image](https://user-images.githubusercontent.com/4706996/39641503-5128c9ee-4fc6-11e8-8316-22e07919005f.png)
> 
> ...this is the full list from the dialog box:
> 
> libreoffice-l10n-en-za
> thunderbird-locale-en-gb
> hunspell-en-au
> hyphen-en-gb
> hunspell-en-gb
> libreoffice-help-en-gb
> gimp-help-en
> hunspell-en-ca
> mythes-en-au
> hunspell-en-za
> libreoffice-l10n-en-gb
> 
> I clicked on "install" and after some files were installed I launched Atom and there was no red error message this time.

This worked for me in xubuntu 19.04 after installing the .deb directly from https://atom.io website. Thank you @Holyprogrammer

**Comment by tank-trax** [comment]
`sudo apt-get install hunspell-en-ca` did it for me

**Comment by ioquatix** [comment]
On arch linux, missing "en-GB":

```
sudo pacman -S hunspell-en_GB" 
```

Solved the issue.

**Comment by pbcornelius** [comment]
On Windows 10 with en-GB installed: when Atom starts it can't find it. Fresh install with Juno, otherwise no settings changed.

![Untitled-1](https://user-images.githubusercontent.com/38129562/81317923-c352e680-908d-11ea-9404-4c03d72467fc.png)

**Comment by realindiahotel** [comment]
On macOS 10.15.4 I unticked the Use Locales option, and made sure the Use System option was checked and this solved the problem for me.

![image](https://user-images.githubusercontent.com/2297007/81490946-66447400-92cb-11ea-81c8-35876a22b2e4.png)

**Comment by pbcornelius** [comment]
That solved it, thanks!

**Comment by withviz** [comment]
Is this issue the same as [https://github.com/atom/spell-check/issues/328](https://github.com/atom/spell-check/issues/328)?

**Comment by Tokuhisa1** [comment]
> On macOS 10.15.4 I unticked the Use Locales option, and made sure the Use System option was checked and this solved the problem for me.
> 
> ![image](https://user-images.githubusercontent.com/2297007/81490946-66447400-92cb-11ea-81c8-35876a22b2e4.png)

How do I navigate there?

**Comment by appsparkler** [comment]
I'm in India on MacOS.  I added `en-IN` in the `packages/spell-check`:

Screenshot for your reference:
<img width="580" alt="image" src="https://user-images.githubusercontent.com/12084821/82524931-c64ddc80-9b4d-11ea-9c67-09db9a7537ff.png">

Thanks & Good Luck 😃

**Comment by 9994444ggg** [comment]
Your Git Hub side is fun thank you.

**Comment by dmoonfire** [comment]
It sounds like this is resolved, so I'm going to close this issue. Feel free to open a new one.
