### ISSUE TITLE
Spell Check doesn't work Ubuntu 18.04

### ISSUE THREAD

**Issue by adavie1** [atom/spell-check#321]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
Despite looking at all the other fixes for this issue- still can't spell check. In my case, HMTL text. Yes, I have `text.html` in the Grammars section.
![image](https://user-images.githubusercontent.com/3030402/78730660-10994680-7970-11ea-90b5-5678f0211bfa.png)
I've also got the **hunspell** package installed, and it's the latest version according to `apt`.

I've checked Developer Mode (Chrome Console) nothing under console, or error logs.

Adding the lthe linter-spell and linter-spell-html packages don't work either.

When I install them I do get an error like this:
![image](https://user-images.githubusercontent.com/3030402/78730970-e6945400-7970-11ea-8d9b-354f8917e6cd.png)
I'm assume the error message might relate to this. Yes, I've read the warning too :-) 

### Steps to Reproduce

1. Check Spelling on HTML doc.
 2. Nothing happens.

**Expected behavior:**
Spelling correction.

**Actual behavior:**
Nothing.

**Reproduces how often:**
Every time.

### Versions

Atom: 1.45.0
Electron: 4.2.7
Chrome: 69.0.3497.128
NodeJS: v10.11.0
Ubuntu: 18.04 (all upgraded to latest versions) as of today.

**Comment by Aerijo** [comment]
Is Hunspell installed?

**Comment by adavie1** [comment]
@Aerijo yes, it is, as noted above, latest version.

**Comment by adavie1** [comment]
@Aerijo any feedback please?

**Comment by Aerijo** [comment]
Oh, I missed that the error was being thrown by the `linter-spell` community package. As the warning box suggests (provided by `linter-spell`), you should disable one of this package or `linter-spell`. If you disable this package, you should report the error to `linter-spell` if it still continues.

**Comment by adavie1** [comment]
@Aerijo as i said above, I have already uninstalled l`inter-spell`. I included it as it might help you identify the problem I'm having. I *still* have the error on `spell-check`. Please re-open this ticket. Thanks and regards.

**Comment by Aerijo** [comment]
I see. Well, I still don't have a clue what the cause might be, but the reason for closing was incorrect.

You can try seeing what the output of the following is when evaluated in dev tools
```
require("child_process").execSync("hunspell --version", {encoding: "utf8"})
```

**Comment by adavie1** [comment]
Thanks @Aerijo. Where do you add that? Or just on the console?

**Comment by Aerijo** [comment]
Just the console

**Comment by dmoonfire** [comment]
The underlying library doesn't use the `hunspell` executable. If you have `linter-spell` disabled, what message do you get? The screenshot only shows linter errors, so I'm not sure the exact error to check it.

**Comment by adavie1** [comment]
@dmoonfire that's the problem, I can't find an error message. Looked into console, nothing. Looked at the Developer Tools, warning and error logs: nothing. Yet it doesn't work!

`linter-spell` was just to test- It has been completely uninstalled.

I've only got `spell-check` active and installed.

**Comment by dmoonfire** [comment]
Try toggling the spell check? `Spell Check: Toggle`?

Also, in the settings for `spell-check`, could you give me a screenshot of your settings? You should probably have `Use Locale` checked (`Use System` does nothing on Linux).

What is your default language? `en-US` or something else?

**Comment by adavie1** [comment]
Apologies for the late reply @dmoonfire .
Tried toggling. Nothing happens.
Here's the screenshot of my settings:
![image](https://user-images.githubusercontent.com/3030402/82514089-4de41d00-9b47-11ea-95d7-130b0eef7799.png)
I've tried unchecking Locale, then checking it with en-US and en-GB. (Both dictionaries are installed).

**Comment by dmoonfire** [comment]
@adavie1, would you please try it out in the latest Atom beta? We've pushed up a bunch of changes which may help with this. Thank you.

**Comment by adavie1** [comment]
@dmoonfire Thanks. I will let you know how it goes.

**Comment by dmoonfire** [comment]
Since there hasn't been any response for a while, I'm going to close this issue. Feel free to reopen.

**Comment by adavie1** [comment]
Still having the problem. But was busy with client projects which prevented further investigation.

**Comment by dmoonfire** [comment]
@adavie1, I can understand that. Since this started, I implemented `debug` for the library. So to turn on logging, you have to run the following on the console.

```
localStorage.debug = 'spell-check:*'
```

Then hit F5 or Control-R in the developer console, that will cause Atom to reload and hopefully you will see a slew of colorful messages that I'm hoping will give more information. Would you please be willing to try this and post the results?

**Comment by adavie1** [comment]
Resolved after new install of Ubuntu 20.04
